### ISSUE TITLE
Better navigation

### ISSUE THREAD

**Issue by 183amir** [TraceSoftwareInternational/HostMyDocs#24]
Hi,

First of all thank you for putting the effort and creating this software.
I have a couple of suggestions which you are free to ignore.

- The navigation through the sidebar is difficult. I kept clicking on the project's name but it was not clickable. I had to click on that tiny arrow on left instead.
- I would like to see the project's documentation as soon as I click on it. This can be the latest uploaded docs or a configurable default path like `project-name/stable/default-language`.
- The fact that you need to specify the programming language of the docs is a bit confusing at first but I think it makes sense if your project has API in different languages. But I was wondering if it would be possible to not show the programming language in the sidebar (one less click) either when the project has only docs in one language or when you configure the server to show the `Python` docs by default as soon as you click on the `version`.
- A default landing page. When you load the first webpage, you land in an empty page that says no project is loaded. I would rather set this to something like: `default-project/stable/default-language`.

**Comment by MattMattV** [comment]
Thanks for your ideas !

Since all related issues that were created with your report are now closed and merged, I think I can close this one, if you have more ideas don't hesitate to post again here or create a new issue and we will get a look at it  (:

**Comment by 183amir** [comment]
Thank you very much. I'll give it a try next week and report back.
