### ISSUE TITLE
Enable text search in all documentation

### ISSUE THREAD

**Issue by osherdp** [TraceSoftwareInternational/HostMyDocs#41]
## Expected Behavior
As a user, I would like to search in the documentation.
The idea is a search bar, that when writing the relevant text in it, it can iterate between occurrences of the text in all documentation (all projects, probably only on the latest version).

## Current Behavior
Currently, one can implement his own search in the documentation using Sphinx for example. But no whole-site search can be performed.

## Possible Solution
Two possibilities:
* Entering the text to search will get into a new page, that includes the results, just like Google.
* Searching just like in a single page app (like searching in the browser). Probably a bit more hard to implement, but more elegant.

## Context
As a solution to hosting documentation for several libraries/products with some relation, it's pretty useful to have the ability to search in all of them.

**Comment by MattMattV** [comment]
Thank you for your feedback !

But the first purpose of HostMyDocs was to only store the documentation for softwares, library or any HTML document and as HTML documentations are very differents (depending of the generator) from one to another, implementing a proper research function like you describe would be painful.

But if you can "override" your documentation generator to change its links, it would be possible to have a link that goes to HostMyDocs opened on another peoject, on a specific page.
