### ISSUE TITLE
Push docker image only in our builds

### ISSUE THREAD

**Issue by MattMattV** [TraceSoftwareInternational/HostMyDocs#47]
In [that][1] build, a new docker image is pushed to our Docker Hub repo, but this build is happening as part of a PR on a forked repository, this must not happen.

[1]: https://travis-ci.org/TraceSoftwareInternational/HostMyDocs/builds/382652382#L1149

**Comment by jonatjano** [comment]
I think it is because the branch in the fork is also called `master`

**Comment by jonatjano** [comment]
you may use [TRAVIS_PULL_REQUEST var](https://docs.travis-ci.com/user/environment-variables/#Convenience-Variables) in `.travis.yml`
