### ISSUE TITLE
Impossible to expand item in left tree

### ISSUE THREAD

**Issue by Ducatel** [TraceSoftwareInternational/HostMyDocs#52]
## Expected Behavior

When click on a top level item tree, it should be expended

## Current Behavior

Nothing append

## Possible Solution

There is a `ReferenceError: customElements is not defined` 

## Steps to Reproduce (for bugs)
1. docker run -d -p 8080:80 [.....] tracesoftware/hostmydocs
2. Push doc sample
3. Go to hostmydocs home page, the left tree doesn't work

## Your Environment

* Version used: latest
* Browser Name and version: Firefox 60.7.0esr
* Operating System and version: Windows 10

**Comment by MattMattV** [comment]
Closed by #53

**Comment by Ducatel** [comment]
tested, it's working thanks ;)
